INSERT INTO city (id,name,cId) VALUES (1,'Baxley',1);
INSERT INTO city (id,name,cId) VALUES (2,'Bristol',1);
INSERT INTO city(id,name,cId) VALUES (3,'Surrency',1);
INSERT INTO city(id,name,cId) VALUES (4,'Axson',2);
INSERT INTO city(id,name,cId) VALUES (5,'Pearson',2);
INSERT INTO city(id,name,cId) VALUES (6,'Willacoochee',2);
INSERT INTO city(id,name,cId) VALUES (7,'Alma',3);
INSERT INTO city(id,name,cId) VALUES (8,'Newton',4);
INSERT INTO city(id,name,cId) VALUES (9,'Hardwick',5);
INSERT INTO city(id,name,cId) VALUES (10,'Milledgeville',5);
INSERT INTO city(id,name,cId) VALUES (11,'Baldwin',6);
INSERT INTO city(id,name,cId) VALUES (12,'Homer',6);
INSERT INTO city(id,name,cId) VALUES (13,'Auburn',7);
INSERT INTO city(id,name,cId) VALUES (14,'Bethlehem',7);
INSERT INTO city(id,name,cId) VALUES (15,'Statham',7);
INSERT INTO city(id,name,cId) VALUES (16,'Winder',7);
INSERT INTO city(id,name,cId) VALUES (17,'Adairsville',8);
INSERT INTO city(id,name,cId) VALUES (18,'Cartersville',8);
INSERT INTO city(id,name,cId) VALUES (19,'Cassville',8);
INSERT INTO city(id,name,cId) VALUES (20,'Emerson',8);
INSERT INTO city(id,name,cId) VALUES (21,'Kingston',8);
INSERT INTO city(id,name,cId) VALUES (22,'Rydal',8);
INSERT INTO city(id,name,cId) VALUES (23,'Taylorsville',8);
INSERT INTO city(id,name,cId) VALUES (24,'White',8);
INSERT INTO city(id,name,cId) VALUES (25,'Fitzgerald',9);
INSERT INTO city(id,name,cId) VALUES (26,'Alapaha',10);
INSERT INTO city(id,name,cId) VALUES (27,'Enigma',10);
INSERT INTO city(id,name,cId) VALUES (28,'Nashville',10);
INSERT INTO city(id,name,cId) VALUES (29,'Ray City',10);
INSERT INTO city(id,name,cId) VALUES (30,'Lizella',11);
INSERT INTO city(id,name,cId) VALUES (31,'Macon',11);
INSERT INTO city(id,name,cId) VALUES (32,'Cochran',12);
INSERT INTO city(id,name,cId) VALUES (33,'Hoboken',13);
INSERT INTO city(id,name,cId) VALUES (34,'Hortense',13);
INSERT INTO city(id,name,cId) VALUES (35,'Nahunta',13);
INSERT INTO city(id,name,cId) VALUES (36,'Waynesville',13);
INSERT INTO city(id,name,cId) VALUES (37,'Barney',14);
INSERT INTO city(id,name,cId) VALUES (38,'Dixie',14);
INSERT INTO city(id,name,cId) VALUES (39,'Morven',14);
INSERT INTO city(id,name,cId) VALUES (40,'Quitman',14);
INSERT INTO city(id,name,cId) VALUES (41,'Ellabell',15);
INSERT INTO city(id,name,cId) VALUES (42,'Pembroke',15);
INSERT INTO city(id,name,cId) VALUES (43,'Richmond Hill',15);
INSERT INTO city(id,name,cId) VALUES (44,'Brooklet',16);
INSERT INTO city(id,name,cId) VALUES (45,'Portal',16);
INSERT INTO city(id,name,cId) VALUES (46,'Register',16);
INSERT INTO city(id,name,cId) VALUES (47,'Statesboro',16);
INSERT INTO city(id,name,cId) VALUES (48,'Girard',17);
INSERT INTO city(id,name,cId) VALUES (49,'Gough',17);
INSERT INTO city(id,name,cId) VALUES (50,'Keysville',17);
INSERT INTO city(id,name,cId) VALUES (51,'Sardis',17);
INSERT INTO city(id,name,cId) VALUES (52,'Waynesboro',17);
INSERT INTO city(id,name,cId) VALUES (53,'Flovilla',18);
INSERT INTO city(id,name,cId) VALUES (54,'Jackson',18);
INSERT INTO city(id,name,cId) VALUES (55,'Jenkinsburg',18);
INSERT INTO city(id,name,cId) VALUES (56,'Arlington',19);
INSERT INTO city(id,name,cId) VALUES (57,'Edison',19);
INSERT INTO city(id,name,cId) VALUES (58,'Leary',19);
INSERT INTO city(id,name,cId) VALUES (59,'Morgan',19);
INSERT INTO city(id,name,cId) VALUES (60,'Kings Bay',20);
INSERT INTO city(id,name,cId) VALUES (61,'Kingsland',20);
INSERT INTO city(id,name,cId) VALUES (62,'Saint Marys',20);
INSERT INTO city(id,name,cId) VALUES (63,'Waverly',20);
INSERT INTO city(id,name,cId) VALUES (64,'White Oak',20);
INSERT INTO city(id,name,cId) VALUES (65,'Woodbine',20);
INSERT INTO city(id,name,cId) VALUES (66,'Metter',21);
INSERT INTO city(id,name,cId) VALUES (67,'Pulaski',21);
INSERT INTO city(id,name,cId) VALUES (68,'Bowdon',22);
INSERT INTO city(id,name,cId) VALUES (69,'Bowdon Junction',22);
INSERT INTO city(id,name,cId) VALUES (70,'Carrollton',22);
INSERT INTO city(id,name,cId) VALUES (71,'Mount Zion',22);
INSERT INTO city(id,name,cId) VALUES (72,'Roopville',22);
INSERT INTO city(id,name,cId) VALUES (73,'Temple',22);
INSERT INTO city(id,name,cId) VALUES (74,'Villa Rica',22);
INSERT INTO city(id,name,cId) VALUES (75,'Waco',22);
INSERT INTO city(id,name,cId) VALUES (76,'Whitesburg',22);
INSERT INTO city(id,name,cId) VALUES (77,'Fort Oglethorpe',23);
INSERT INTO city(id,name,cId) VALUES (78,'Graysville',23);
INSERT INTO city(id,name,cId) VALUES (79,'Ringgold',23);
INSERT INTO city(id,name,cId) VALUES (80,'Folkston',24);
INSERT INTO city(id,name,cId) VALUES (81,'Saint George',24);
INSERT INTO city(id,name,cId) VALUES (82,'Pooler',25);
INSERT INTO city(id,name,cId) VALUES (83,'Savannah',25);
INSERT INTO city(id,name,cId) VALUES (84,'Tybee Island',25);
INSERT INTO city(id,name,cId) VALUES (85,'Cusseta',26);
INSERT INTO city(id,name,cId) VALUES (86,'Fort Benning',26);
INSERT INTO city(id,name,cId) VALUES (87,'Lyerly',27);
INSERT INTO city(id,name,cId) VALUES (88,'Menlo',27);
INSERT INTO city(id,name,cId) VALUES (89,'Summerville',27);
INSERT INTO city(id,name,cId) VALUES (90,'Trion',27);
INSERT INTO city(id,name,cId) VALUES (91,'Ball Ground',28);
INSERT INTO city(id,name,cId) VALUES (92,'Canton',28);
INSERT INTO city(id,name,cId) VALUES (93,'Holly Springs',28);
INSERT INTO city(id,name,cId) VALUES (94,'Lebanon',28);
INSERT INTO city(id,name,cId) VALUES (95,'Waleska',28);
INSERT INTO city(id,name,cId) VALUES (96,'Woodstock',28);
INSERT INTO city(id,name,cId) VALUES (97,'Athens',29);
INSERT INTO city(id,name,cId) VALUES (98,'Winterville',29);
INSERT INTO city(id,name,cId) VALUES (99,'Bluffton',30);
INSERT INTO city(id,name,cId) VALUES (100,'Fort Gaines',30);
INSERT INTO city(id,name,cId) VALUES (101,'Morris',30);
INSERT INTO city(id,name,cId) VALUES (102,'Conley',31);
INSERT INTO city(id,name,cId) VALUES (103,'Forest Park',31);
INSERT INTO city(id,name,cId) VALUES (104,'Jonesboro',31);
INSERT INTO city(id,name,cId) VALUES (105,'Lovejoy',31);
INSERT INTO city(id,name,cId) VALUES (106,'Morrow',31);
INSERT INTO city(id,name,cId) VALUES (107,'Rex',31);
INSERT INTO city(id,name,cId) VALUES (108,'Riverdale',31);
INSERT INTO city(id,name,cId) VALUES (109,'Esom Hill',31);
INSERT INTO city(id,name,cId) VALUES (110,'Argyle',32);
INSERT INTO city(id,name,cId) VALUES (111,'Du Pont',32);
INSERT INTO city(id,name,cId) VALUES (112,'Fargo',32);
INSERT INTO city(id,name,cId) VALUES (113,'Homerville',32);
INSERT INTO city(id,name,cId) VALUES (114,'Acworth',33);
INSERT INTO city(id,name,cId) VALUES (115,'Austell',33);
INSERT INTO city(id,name,cId) VALUES (116,'Clarkdale',33);
INSERT INTO city(id,name,cId) VALUES (117,'Kennesaw',33);
INSERT INTO city(id,name,cId) VALUES (118,'Mableton',33);
INSERT INTO city(id,name,cId) VALUES (119,'Marietta',33);
INSERT INTO city(id,name,cId) VALUES (120,'Powder Springs',33);
INSERT INTO city(id,name,cId) VALUES (121,'Smyrna',33);
INSERT INTO city(id,name,cId) VALUES (122,'Ambrose',34);
INSERT INTO city(id,name,cId) VALUES (123,'Broxton',34);
INSERT INTO city(id,name,cId) VALUES (124,'Douglas',34);
INSERT INTO city(id,name,cId) VALUES (125,'Nicholls',34);
INSERT INTO city(id,name,cId) VALUES (126,'West Green',34);
INSERT INTO city(id,name,cId) VALUES (127,'Berlin',35);
INSERT INTO city(id,name,cId) VALUES (128,'Doerun',35);
INSERT INTO city(id,name,cId) VALUES (129,'Ellenton',35);
INSERT INTO city(id,name,cId) VALUES (130,'Funston',35);
INSERT INTO city(id,name,cId) VALUES (131,'Hartsfield',35);
INSERT INTO city(id,name,cId) VALUES (132,'Moultrie',35);
INSERT INTO city(id,name,cId) VALUES (133,'Norman Park',35);
INSERT INTO city(id,name,cId) VALUES (134,'Appling',36);
INSERT INTO city(id,name,cId) VALUES (135,'Evans',36);
INSERT INTO city(id,name,cId) VALUES (136,'Grovetown',36);
INSERT INTO city(id,name,cId) VALUES (137,'Harlem',36);
INSERT INTO city(id,name,cId) VALUES (138,'Adel',37);
INSERT INTO city(id,name,cId) VALUES (139,'Cecil',37);
INSERT INTO city(id,name,cId) VALUES (140,'Lenox',37);
INSERT INTO city(id,name,cId) VALUES (141,'Sparks',37);
INSERT INTO city(id,name,cId) VALUES (142,'Grantville',38);
INSERT INTO city(id,name,cId) VALUES (143,'Haralson',38);
INSERT INTO city(id,name,cId) VALUES (144,'Moreland',38);
INSERT INTO city(id,name,cId) VALUES (145,'Newnan',38);
INSERT INTO city(id,name,cId) VALUES (146,'Sargent',38);
INSERT INTO city(id,name,cId) VALUES (147,'Senoia',38);
INSERT INTO city(id,name,cId) VALUES (148,'Sharpsburg',38);
INSERT INTO city(id,name,cId) VALUES (149,'Turin',38);
INSERT INTO city(id,name,cId) VALUES (150,'Knoxville',39);
INSERT INTO city(id,name,cId) VALUES (151,'Musella',39);
INSERT INTO city(id,name,cId) VALUES (152,'Roberta',39);
INSERT INTO city(id,name,cId) VALUES (153,'Arabi',40);
INSERT INTO city(id,name,cId) VALUES (154,'Cordele',40);
INSERT INTO city(id,name,cId) VALUES (155,'Rising Fawn',41);
INSERT INTO city(id,name,cId) VALUES (156,'Trenton',41);
INSERT INTO city(id,name,cId) VALUES (157,'Wildwood',41);
INSERT INTO city(id,name,cId) VALUES (158,'Dawsonville',42);
INSERT INTO city(id,name,cId) VALUES (159,'Attapulgus',43);
INSERT INTO city(id,name,cId) VALUES (160,'Bainbridge',43);
INSERT INTO city(id,name,cId) VALUES (161,'Brinson',43);
INSERT INTO city(id,name,cId) VALUES (162,'Climax',43);
INSERT INTO city(id,name,cId) VALUES (163,'Fowlstown',43);
INSERT INTO city(id,name,cId) VALUES (164,'Avondale Estates',44);
INSERT INTO city(id,name,cId) VALUES (165,'Clarkston',44);
INSERT INTO city(id,name,cId) VALUES (166,'Decatur',44);
INSERT INTO city(id,name,cId) VALUES (167,'Ellenwood',44);
INSERT INTO city(id,name,cId) VALUES (168,'Lithonia',44);
INSERT INTO city(id,name,cId) VALUES (169,'Pine Lake',44);
INSERT INTO city(id,name,cId) VALUES (170,'Redan',44);
INSERT INTO city(id,name,cId) VALUES (171,'Scottdale',44);
INSERT INTO city(id,name,cId) VALUES (172,'Stone Mountain',44);
INSERT INTO city(id,name,cId) VALUES (173,'Tucker',44);
INSERT INTO city(id,name,cId) VALUES (174,'Chauncey',45);
INSERT INTO city(id,name,cId) VALUES (175,'Chester',45);
INSERT INTO city(id,name,cId) VALUES (176,'Eastman',45);
INSERT INTO city(id,name,cId) VALUES (177,'Rhine',45);
INSERT INTO city(id,name,cId) VALUES (178,'Byromville',46);
INSERT INTO city(id,name,cId) VALUES (179,'Lilly',46);
INSERT INTO city(id,name,cId) VALUES (180,'Pinehurst',46);
INSERT INTO city(id,name,cId) VALUES (181,'Unadilla',46);
INSERT INTO city(id,name,cId) VALUES (182,'Vienna',46);
INSERT INTO city(id,name,cId) VALUES (183,'Albany',47);
INSERT INTO city(id,name,cId) VALUES (184,'Putney',47);
INSERT INTO city(id,name,cId) VALUES (185,'Douglasville',48);
INSERT INTO city(id,name,cId) VALUES (186,'Lithia Springs',48);
INSERT INTO city(id,name,cId) VALUES (187,'Winston',48);
INSERT INTO city(id,name,cId) VALUES (188,'Blakely',49);
INSERT INTO city(id,name,cId) VALUES (189,'Cedar Springs',49);
INSERT INTO city(id,name,cId) VALUES (190,'Damascus',49);
INSERT INTO city(id,name,cId) VALUES (191,'Jakin',49);
INSERT INTO city(id,name,cId) VALUES (192,'Statenville',50);
INSERT INTO city(id,name,cId) VALUES (193,'Bloomingdale',51);
INSERT INTO city(id,name,cId) VALUES (194,'Clyo',51);
INSERT INTO city(id,name,cId) VALUES (195,'Eden',51);
INSERT INTO city(id,name,cId) VALUES (196,'Guyton',51);
INSERT INTO city(id,name,cId) VALUES (197,'Meldrim',51);
INSERT INTO city(id,name,cId) VALUES (198,'Rincon',51);
INSERT INTO city(id,name,cId) VALUES (199,'Springfield',51);
INSERT INTO city(id,name,cId) VALUES (200,'Bowman',52);
INSERT INTO city(id,name,cId) VALUES (201,'Dewy Rose',52);
INSERT INTO city(id,name,cId) VALUES (202,'Elberton',52);
INSERT INTO city(id,name,cId) VALUES (203,'Adrian',53);
INSERT INTO city(id,name,cId) VALUES (204,'Garfield',53);
INSERT INTO city(id,name,cId) VALUES (205,'Midville',53);
INSERT INTO city(id,name,cId) VALUES (206,'Norristown',53);
INSERT INTO city(id,name,cId) VALUES (207,'Nunez',53);
INSERT INTO city(id,name,cId) VALUES (208,'Stillmore',53);
INSERT INTO city(id,name,cId) VALUES (209,'Swainsboro',53);
INSERT INTO city(id,name,cId) VALUES (210,'Twin City',53);
INSERT INTO city(id,name,cId) VALUES (211,'Bellville',54);
INSERT INTO city(id,name,cId) VALUES (212,'Claxton',54);
INSERT INTO city(id,name,cId) VALUES (213,'Daisy',54);
INSERT INTO city(id,name,cId) VALUES (214,'Hagan',54);
INSERT INTO city(id,name,cId) VALUES (215,'Blue Ridge',55);
INSERT INTO city(id,name,cId) VALUES (216,'Epworth',55);
INSERT INTO city(id,name,cId) VALUES (217,'Mc Caysville',55);
INSERT INTO city(id,name,cId) VALUES (218,'Mineral Bluff',55);
INSERT INTO city(id,name,cId) VALUES (219,'Morganton',55);
INSERT INTO city(id,name,cId) VALUES (220,'Brooks',56);
INSERT INTO city(id,name,cId) VALUES (221,'Fayetteville',56);
INSERT INTO city(id,name,cId) VALUES (222,'Peachtree City',56);
INSERT INTO city(id,name,cId) VALUES (223,'Tyrone',56);
INSERT INTO city(id,name,cId) VALUES (224,'Armuchee',57);
INSERT INTO city(id,name,cId) VALUES (225,'Cave Spring',57);
INSERT INTO city(id,name,cId) VALUES (226,'Coosa',57);
INSERT INTO city(id,name,cId) VALUES (227,'Lindale',57);
INSERT INTO city(id,name,cId) VALUES (228,'Mount Berry',57);
INSERT INTO city(id,name,cId) VALUES (229,'Rome',57);
INSERT INTO city(id,name,cId) VALUES (230,'Shannon',57);
INSERT INTO city(id,name,cId) VALUES (231,'Silver Creek',57);
INSERT INTO city(id,name,cId) VALUES (232,'Cumming',58);
INSERT INTO city(id,name,cId) VALUES (233,'Canon',59);
INSERT INTO city(id,name,cId) VALUES (234,'Carnesville',59);
INSERT INTO city(id,name,cId) VALUES (235,'Franklin Springs',59);
INSERT INTO city(id,name,cId) VALUES (236,'Lavonia',59);
INSERT INTO city(id,name,cId) VALUES (237,'Royston',59);
INSERT INTO city(id,name,cId) VALUES (238,'Alpharetta',60);
INSERT INTO city(id,name,cId) VALUES (239,'Atlanta',60);
INSERT INTO city(id,name,cId) VALUES (240,'Fairburn',60);
INSERT INTO city(id,name,cId) VALUES (241,'Palmetto',60);
INSERT INTO city(id,name,cId) VALUES (242,'Red Oak',60);
INSERT INTO city(id,name,cId) VALUES (243,'Roswell',60);
INSERT INTO city(id,name,cId) VALUES (244,'Union City',60);
INSERT INTO city(id,name,cId) VALUES (245,'Cherry Log',61);
INSERT INTO city(id,name,cId) VALUES (246,'East Ellijay',61);
INSERT INTO city(id,name,cId) VALUES (247,'Ellijay',61);
INSERT INTO city(id,name,cId) VALUES (248,'Gibson',62);
INSERT INTO city(id,name,cId) VALUES (249,'Mitchell',62);
INSERT INTO city(id,name,cId) VALUES (250,'Brunswick',63);
INSERT INTO city(id,name,cId) VALUES (251,'Jekyll Island',63);
INSERT INTO city(id,name,cId) VALUES (252,'Saint Simons Island',63);
INSERT INTO city(id,name,cId) VALUES (253,'Sea Island',63);
INSERT INTO city(id,name,cId) VALUES (254,'Calhoun',64);
INSERT INTO city(id,name,cId) VALUES (255,'Fairmount',64);
INSERT INTO city(id,name,cId) VALUES (256,'Oakman',64);
INSERT INTO city(id,name,cId) VALUES (257,'Plainville',64);
INSERT INTO city(id,name,cId) VALUES (258,'Ranger',64);
INSERT INTO city(id,name,cId) VALUES (259,'Resaca',64);
INSERT INTO city(id,name,cId) VALUES (260,'Sugar Valley',64);
INSERT INTO city(id,name,cId) VALUES (261,'Cairo',65);
INSERT INTO city(id,name,cId) VALUES (262,'Calvary',65);
INSERT INTO city(id,name,cId) VALUES (263,'Whigham',65);
INSERT INTO city(id,name,cId) VALUES (264,'Greensboro',66);
INSERT INTO city(id,name,cId) VALUES (265,'Siloam',66);
INSERT INTO city(id,name,cId) VALUES (266,'Union Point',66);
INSERT INTO city(id,name,cId) VALUES (267,'White Plains',66);
INSERT INTO city(id,name,cId) VALUES (268,'Buford',67);
INSERT INTO city(id,name,cId) VALUES (269,'Dacula',67);
INSERT INTO city(id,name,cId) VALUES (270,'Duluth',67);
INSERT INTO city(id,name,cId) VALUES (271,'Grayson',67);
INSERT INTO city(id,name,cId) VALUES (272,'Lawrenceville',67);
INSERT INTO city(id,name,cId) VALUES (273,'Lilburn',67);
INSERT INTO city(id,name,cId) VALUES (274,'Norcross',67);
INSERT INTO city(id,name,cId) VALUES (275,'North Metro',67);
INSERT INTO city(id,name,cId) VALUES (276,'Snellville',67);
INSERT INTO city(id,name,cId) VALUES (277,'Suwanee',67);
INSERT INTO city(id,name,cId) VALUES (278,'Alto',68);
INSERT INTO city(id,name,cId) VALUES (279,'Clarkesville',68);
INSERT INTO city(id,name,cId) VALUES (280,'Cornelia',68);
INSERT INTO city(id,name,cId) VALUES (281,'Demorest',68);
INSERT INTO city(id,name,cId) VALUES (282,'Habersham',68);
INSERT INTO city(id,name,cId) VALUES (283,'Mount Airy',68);
INSERT INTO city(id,name,cId) VALUES (284,'Turnerville',68);
INSERT INTO city(id,name,cId) VALUES (285,'Chestnut Mountain',69);
INSERT INTO city(id,name,cId) VALUES (286,'Clermont',69);
INSERT INTO city(id,name,cId) VALUES (287,'Flowery Branch',69);
INSERT INTO city(id,name,cId) VALUES (288,'Gainesville',69);
INSERT INTO city(id,name,cId) VALUES (289,'Gillsville',69);
INSERT INTO city(id,name,cId) VALUES (290,'Lula',69);
INSERT INTO city(id,name,cId) VALUES (291,'Murrayville',69);
INSERT INTO city(id,name,cId) VALUES (292,'Oakwood',69);
INSERT INTO city(id,name,cId) VALUES (293,'Sparta',70);
INSERT INTO city(id,name,cId) VALUES (294,'Bremen',71);
INSERT INTO city(id,name,cId) VALUES (295,'Buchanan',71);
INSERT INTO city(id,name,cId) VALUES (296,'Felton',71);
INSERT INTO city(id,name,cId) VALUES (297,'Tallapoosa',71);
INSERT INTO city(id,name,cId) VALUES (298,'Cataula',72);
INSERT INTO city(id,name,cId) VALUES (299,'Ellerslie',72);
INSERT INTO city(id,name,cId) VALUES (300,'Fortson',72);
INSERT INTO city(id,name,cId) VALUES (301,'Hamilton',72);
INSERT INTO city(id,name,cId) VALUES (302,'Pine Mountain',72);
INSERT INTO city(id,name,cId) VALUES (303,'Pine Mountain Valley',72);
INSERT INTO city(id,name,cId) VALUES (304,'Shiloh',72);
INSERT INTO city(id,name,cId) VALUES (305,'Waverly Hall',72);
INSERT INTO city(id,name,cId) VALUES (306,'Bowersville',73);
INSERT INTO city(id,name,cId) VALUES (307,'Hartwell',73);
INSERT INTO city(id,name,cId) VALUES (308,'Franklin',74);
INSERT INTO city(id,name,cId) VALUES (309,'Glenn',74);
INSERT INTO city(id,name,cId) VALUES (310,'Hampton',75);
INSERT INTO city(id,name,cId) VALUES (311,'Locust Grove',75);
INSERT INTO city(id,name,cId) VALUES (312,'Mcdonough',75);
INSERT INTO city(id,name,cId) VALUES (313,'Stockbridge',75);
INSERT INTO city(id,name,cId) VALUES (314,'Bonaire',76);
INSERT INTO city(id,name,cId) VALUES (315,'Centerville',76);
INSERT INTO city(id,name,cId) VALUES (316,'Clinchfield',76);
INSERT INTO city(id,name,cId) VALUES (317,'Elko',76);
INSERT INTO city(id,name,cId) VALUES (318,'Kathleen',76);
INSERT INTO city(id,name,cId) VALUES (319,'Perry',76);
INSERT INTO city(id,name,cId) VALUES (320,'Warner Robins',76);
INSERT INTO city(id,name,cId) VALUES (321,'Irwinville',77);
INSERT INTO city(id,name,cId) VALUES (322,'Mystic',77);
INSERT INTO city(id,name,cId) VALUES (323,'Ocilla',77);
INSERT INTO city(id,name,cId) VALUES (324,'Wray',77);
INSERT INTO city(id,name,cId) VALUES (325,'Braselton',78);
INSERT INTO city(id,name,cId) VALUES (326,'Commerce',78);
INSERT INTO city(id,name,cId) VALUES (327,'Hoschton',78);
INSERT INTO city(id,name,cId) VALUES (328,'Jefferson',78);
INSERT INTO city(id,name,cId) VALUES (329,'Maysville',78);
INSERT INTO city(id,name,cId) VALUES (330,'Nicholson',78);
INSERT INTO city(id,name,cId) VALUES (331,'Pendergrass',78);
INSERT INTO city(id,name,cId) VALUES (332,'Talmo',78);
INSERT INTO city(id,name,cId) VALUES (333,'Hillsboro',79);
INSERT INTO city(id,name,cId) VALUES (334,'Mansfield',79);
INSERT INTO city(id,name,cId) VALUES (335,'Monticello',79);
INSERT INTO city(id,name,cId) VALUES (336,'Newborn',79);
INSERT INTO city(id,name,cId) VALUES (337,'Shady Dale',79);
INSERT INTO city(id,name,cId) VALUES (338,'Denton',80);
INSERT INTO city(id,name,cId) VALUES (339,'Hazlehurst',80);
INSERT INTO city(id,name,cId) VALUES (340,'Avera',81);
INSERT INTO city(id,name,cId) VALUES (341,'Bartow',81);
INSERT INTO city(id,name,cId) VALUES (342,'Louisville',81);
INSERT INTO city(id,name,cId) VALUES (343,'Matthews',81);
INSERT INTO city(id,name,cId) VALUES (344,'Stapleton',81);
INSERT INTO city(id,name,cId) VALUES (345,'Wadley',81);
INSERT INTO city(id,name,cId) VALUES (346,'Wrens',81);
INSERT INTO city(id,name,cId) VALUES (347,'Millen',82);
INSERT INTO city(id,name,cId) VALUES (348,'Perkins',82);
INSERT INTO city(id,name,cId) VALUES (349,'Kite',83);
INSERT INTO city(id,name,cId) VALUES (350,'Wrightsville',83);
INSERT INTO city(id,name,cId) VALUES (351,'Gray',84);
INSERT INTO city(id,name,cId) VALUES (352,'Haddock',84);
INSERT INTO city(id,name,cId) VALUES (353,'Barnesville',85);
INSERT INTO city(id,name,cId) VALUES (354,'Milner',85);
INSERT INTO city(id,name,cId) VALUES (355,'Lakeland',86);
INSERT INTO city(id,name,cId) VALUES (356,'Stockton',86);
INSERT INTO city(id,name,cId) VALUES (357,'Cadwell',87);
INSERT INTO city(id,name,cId) VALUES (358,'Dexter',87);
INSERT INTO city(id,name,cId) VALUES (359,'Dublin',87);
INSERT INTO city(id,name,cId) VALUES (360,'Dudley',87);
INSERT INTO city(id,name,cId) VALUES (361,'East Dublin',87);
INSERT INTO city(id,name,cId) VALUES (362,'Montrose',87);
INSERT INTO city(id,name,cId) VALUES (363,'Rentz',87);
INSERT INTO city(id,name,cId) VALUES (364,'Rockledge',87);
INSERT INTO city(id,name,cId) VALUES (365,'Leesburg',88);
INSERT INTO city(id,name,cId) VALUES (366,'Smithville',88);
INSERT INTO city(id,name,cId) VALUES (367,'Allenhurst',89);
INSERT INTO city(id,name,cId) VALUES (368,'Fleming',89);
INSERT INTO city(id,name,cId) VALUES (369,'Fort Stewart',89);
INSERT INTO city(id,name,cId) VALUES (370,'Hinesville',89);
INSERT INTO city(id,name,cId) VALUES (371,'Midway',89);
INSERT INTO city(id,name,cId) VALUES (372,'Riceboro',89);
INSERT INTO city(id,name,cId) VALUES (373,'Walthourville',89);
INSERT INTO city(id,name,cId) VALUES (374,'Lincolnton',90);
INSERT INTO city(id,name,cId) VALUES (375,'Ludowici',91);
INSERT INTO city(id,name,cId) VALUES (376,'Hahira',92);
INSERT INTO city(id,name,cId) VALUES (377,'Lake Park',92);
INSERT INTO city(id,name,cId) VALUES (378,'Moody A F B',92);
INSERT INTO city(id,name,cId) VALUES (379,'Naylor',92);
INSERT INTO city(id,name,cId) VALUES (380,'Valdosta',92);
INSERT INTO city(id,name,cId) VALUES (381,'Dahlonega',93);
INSERT INTO city(id,name,cId) VALUES (382,'Ideal',94);
INSERT INTO city(id,name,cId) VALUES (383,'Marshallville',94);
INSERT INTO city(id,name,cId) VALUES (384,'Montezuma',94);
INSERT INTO city(id,name,cId) VALUES (385,'Oglethorpe',94);
INSERT INTO city(id,name,cId) VALUES (386,'Colbert',95);
INSERT INTO city(id,name,cId) VALUES (387,'Comer',95);
INSERT INTO city(id,name,cId) VALUES (388,'Danielsville',95);
INSERT INTO city(id,name,cId) VALUES (389,'Hull',95);
INSERT INTO city(id,name,cId) VALUES (390,'Ila',95);
INSERT INTO city(id,name,cId) VALUES (391,'Box Springs',96);
INSERT INTO city(id,name,cId) VALUES (392,'Buena Vista',96);
INSERT INTO city(id,name,cId) VALUES (393,'Mauk',96);
INSERT INTO city(id,name,cId) VALUES (394,'Boneville',97);
INSERT INTO city(id,name,cId) VALUES (395,'Dearing',97);
INSERT INTO city(id,name,cId) VALUES (396,'Thomson',97);
INSERT INTO city(id,name,cId) VALUES (397,'Crescent',98);
INSERT INTO city(id,name,cId) VALUES (398,'Darien',98);
INSERT INTO city(id,name,cId) VALUES (399,'Meridian',98);
INSERT INTO city(id,name,cId) VALUES (400,'Sapelo Island',98);
INSERT INTO city(id,name,cId) VALUES (401,'Townsend',98);
INSERT INTO city(id,name,cId) VALUES (402,'Gay',99);
INSERT INTO city(id,name,cId) VALUES (403,'Greenville',99);
INSERT INTO city(id,name,cId) VALUES (404,'Luthersville',99);
INSERT INTO city(id,name,cId) VALUES (405,'Manchester',99);
INSERT INTO city(id,name,cId) VALUES (406,'Warm Springs',99);
INSERT INTO city(id,name,cId) VALUES (407,'Woodbury',99);
INSERT INTO city(id,name,cId) VALUES (408,'Colquitt',100);
INSERT INTO city(id,name,cId) VALUES (409,'Baconton',101);
INSERT INTO city(id,name,cId) VALUES (410,'Camilla',101);
INSERT INTO city(id,name,cId) VALUES (411,'Cotton',101);
INSERT INTO city(id,name,cId) VALUES (412,'Pelham',101);
INSERT INTO city(id,name,cId) VALUES (413,'Sale City',101);
INSERT INTO city(id,name,cId) VALUES (414,'Bolingbroke',102);
INSERT INTO city(id,name,cId) VALUES (415,'Culloden',102);
INSERT INTO city(id,name,cId) VALUES (416,'Forsyth',102);
INSERT INTO city(id,name,cId) VALUES (417,'Juliette',102);
INSERT INTO city(id,name,cId) VALUES (418,'Smarr',102);
INSERT INTO city(id,name,cId) VALUES (419,'Ailey',103);
INSERT INTO city(id,name,cId) VALUES (420,'Alston',103);
INSERT INTO city(id,name,cId) VALUES (421,'Mount Vernon',103);
INSERT INTO city(id,name,cId) VALUES (422,'Tarrytown',103);
INSERT INTO city(id,name,cId) VALUES (423,'Uvalda',103);
INSERT INTO city(id,name,cId) VALUES (424,'Bostwick',104);
INSERT INTO city(id,name,cId) VALUES (425,'Buckhead',104);
INSERT INTO city(id,name,cId) VALUES (426,'Madison',104);
INSERT INTO city(id,name,cId) VALUES (427,'Rutledge',104);
INSERT INTO city(id,name,cId) VALUES (428,'Chatsworth',105);
INSERT INTO city(id,name,cId) VALUES (429,'Cisco',105);
INSERT INTO city(id,name,cId) VALUES (430,'Crandall',105);
INSERT INTO city(id,name,cId) VALUES (431,'Eton',105);
INSERT INTO city(id,name,cId) VALUES (432,'Tennga',105);
INSERT INTO city(id,name,cId) VALUES (433,'Columbus',106);
INSERT INTO city(id,name,cId) VALUES (434,'Midland',106);
INSERT INTO city(id,name,cId) VALUES (435,'Upatoi',106);
INSERT INTO city(id,name,cId) VALUES (436,'Covington',107);
INSERT INTO city(id,name,cId) VALUES (437,'Oxford',107);
INSERT INTO city(id,name,cId) VALUES (438,'Porterdale',107);
INSERT INTO city(id,name,cId) VALUES (439,'Bishop',108);
INSERT INTO city(id,name,cId) VALUES (440,'Bogart',108);
INSERT INTO city(id,name,cId) VALUES (441,'Farmington',108);
INSERT INTO city(id,name,cId) VALUES (442,'Watkinsville',108);
INSERT INTO city(id,name,cId) VALUES (443,'Arnoldsville',109);
INSERT INTO city(id,name,cId) VALUES (444,'Carlton',109);
INSERT INTO city(id,name,cId) VALUES (445,'Crawford',109);
INSERT INTO city(id,name,cId) VALUES (446,'Lexington',109);
INSERT INTO city(id,name,cId) VALUES (447,'Maxeys',109);
INSERT INTO city(id,name,cId) VALUES (448,'Stephens',109);
INSERT INTO city(id,name,cId) VALUES (449,'Dallas',110);
INSERT INTO city(id,name,cId) VALUES (450,'Hiram',110);
INSERT INTO city(id,name,cId) VALUES (451,'Byron',111);
INSERT INTO city(id,name,cId) VALUES (452,'Fort Valley',111);
INSERT INTO city(id,name,cId) VALUES (453,'Jasper',112);
INSERT INTO city(id,name,cId) VALUES (454,'Marble Hill',112);
INSERT INTO city(id,name,cId) VALUES (455,'Nelson',112);
INSERT INTO city(id,name,cId) VALUES (456,'Talking Rock',112);
INSERT INTO city(id,name,cId) VALUES (457,'Tate',112);
INSERT INTO city(id,name,cId) VALUES (458,'Blackshear',113);
INSERT INTO city(id,name,cId) VALUES (459,'Mershon',113);
INSERT INTO city(id,name,cId) VALUES (460,'Offerman',113);
INSERT INTO city(id,name,cId) VALUES (461,'Patterson',113);
INSERT INTO city(id,name,cId) VALUES (462,'Concord',114);
INSERT INTO city(id,name,cId) VALUES (463,'Meansville',114);
INSERT INTO city(id,name,cId) VALUES (464,'Molena',114);
INSERT INTO city(id,name,cId) VALUES (465,'Williamson',114);
INSERT INTO city(id,name,cId) VALUES (466,'Zebulon',114);
INSERT INTO city(id,name,cId) VALUES (467,'Aragon',115);
INSERT INTO city(id,name,cId) VALUES (468,'Cedartown',115);
INSERT INTO city(id,name,cId) VALUES (469,'Rockmart',115);
INSERT INTO city(id,name,cId) VALUES (470,'Hawkinsville',116);
INSERT INTO city(id,name,cId) VALUES (471,'Eatonton',117);
INSERT INTO city(id,name,cId) VALUES (472,'Georgetown',118);
INSERT INTO city(id,name,cId) VALUES (473,'Clayton',119);
INSERT INTO city(id,name,cId) VALUES (474,'Dillard',119);
INSERT INTO city(id,name,cId) VALUES (475,'Lakemont',119);
INSERT INTO city(id,name,cId) VALUES (476,'Mountain City',119);
INSERT INTO city(id,name,cId) VALUES (477,'Rabun Gap',119);
INSERT INTO city(id,name,cId) VALUES (478,'Tallulah Falls',119);
INSERT INTO city(id,name,cId) VALUES (479,'Tiger',119);
INSERT INTO city(id,name,cId) VALUES (480,'Wiley',119);
INSERT INTO city(id,name,cId) VALUES (481,'Coleman',120);
INSERT INTO city(id,name,cId) VALUES (482,'Cuthbert',120);
INSERT INTO city(id,name,cId) VALUES (483,'Shellman',120);
INSERT INTO city(id,name,cId) VALUES (484,'Augusta',121);
INSERT INTO city(id,name,cId) VALUES (485,'Blythe',121);
INSERT INTO city(id,name,cId) VALUES (486,'Gracewood',121);
INSERT INTO city(id,name,cId) VALUES (487,'Hephzibah',121);
INSERT INTO city(id,name,cId) VALUES (488,'Conyers',122);
INSERT INTO city(id,name,cId) VALUES (489,'Ellaville',123);
INSERT INTO city(id,name,cId) VALUES (490,'Dover',124);
INSERT INTO city(id,name,cId) VALUES (491,'Newington',124);
INSERT INTO city(id,name,cId) VALUES (492,'Oliver',124);
INSERT INTO city(id,name,cId) VALUES (493,'Rocky Ford',124);
INSERT INTO city(id,name,cId) VALUES (494,'Sylvania',124);
INSERT INTO city(id,name,cId) VALUES (495,'Donalsonville',125);
INSERT INTO city(id,name,cId) VALUES (496,'Iron City',125);
INSERT INTO city(id,name,cId) VALUES (497,'Experiment',126);
INSERT INTO city(id,name,cId) VALUES (498,'Griffin',126);
INSERT INTO city(id,name,cId) VALUES (499,'Orchard Hill',126);
INSERT INTO city(id,name,cId) VALUES (500,'Sunny Side',126);
INSERT INTO city(id,name,cId) VALUES (501,'Eastanollee',127);
INSERT INTO city(id,name,cId) VALUES (502,'Martin',127);
INSERT INTO city(id,name,cId) VALUES (503,'Toccoa',127);
INSERT INTO city(id,name,cId) VALUES (504,'Toccoa Falls',127);
INSERT INTO city(id,name,cId) VALUES (505,'Louvale',128);
INSERT INTO city(id,name,cId) VALUES (506,'Lumpkin',128);
INSERT INTO city(id,name,cId) VALUES (507,'Omaha',128);
INSERT INTO city(id,name,cId) VALUES (508,'Richland',128);
INSERT INTO city(id,name,cId) VALUES (509,'Americus',129);
INSERT INTO city(id,name,cId) VALUES (510,'Andersonville',129);
INSERT INTO city(id,name,cId) VALUES (511,'Cobb',129);
INSERT INTO city(id,name,cId) VALUES (512,'De Soto',129);
INSERT INTO city(id,name,cId) VALUES (513,'Leslie',129);
INSERT INTO city(id,name,cId) VALUES (514,'Plains',129);
INSERT INTO city(id,name,cId) VALUES (515,'Geneva',130);
INSERT INTO city(id,name,cId) VALUES (516,'Junction City',130);
INSERT INTO city(id,name,cId) VALUES (517,'Talbotton',130);
INSERT INTO city(id,name,cId) VALUES (518,'Woodland',130);
INSERT INTO city(id,name,cId) VALUES (519,'Crawfordville',131);
INSERT INTO city(id,name,cId) VALUES (520,'Sharon',131);
INSERT INTO city(id,name,cId) VALUES (521,'Cobbtown',132);
INSERT INTO city(id,name,cId) VALUES (522,'Collins',132);
INSERT INTO city(id,name,cId) VALUES (523,'Glennville',132);
INSERT INTO city(id,name,cId) VALUES (524,'Manassas',132);
INSERT INTO city(id,name,cId) VALUES (525,'Reidsville',132);
INSERT INTO city(id,name,cId) VALUES (526,'Butler',133);
INSERT INTO city(id,name,cId) VALUES (527,'Howard',133);
INSERT INTO city(id,name,cId) VALUES (528,'Reynolds',133);
INSERT INTO city(id,name,cId) VALUES (529,'Rupert',133);
INSERT INTO city(id,name,cId) VALUES (530,'Helena',134);
INSERT INTO city(id,name,cId) VALUES (531,'Jacksonville',134);
INSERT INTO city(id,name,cId) VALUES (532,'Lumber City',134);
INSERT INTO city(id,name,cId) VALUES (533,'Mc Rae',134);
INSERT INTO city(id,name,cId) VALUES (534,'Milan',134);
INSERT INTO city(id,name,cId) VALUES (535,'Scotland',134);
INSERT INTO city(id,name,cId) VALUES (536,'Bronwood',135);
INSERT INTO city(id,name,cId) VALUES (537,'Dawson',135);
INSERT INTO city(id,name,cId) VALUES (538,'Parrott',135);
INSERT INTO city(id,name,cId) VALUES (539,'Sasser',135);
INSERT INTO city(id,name,cId) VALUES (540,'Barwick',136);
INSERT INTO city(id,name,cId) VALUES (541,'Boston',136);
INSERT INTO city(id,name,cId) VALUES (542,'Coolidge',136);
INSERT INTO city(id,name,cId) VALUES (543,'Meigs',136);
INSERT INTO city(id,name,cId) VALUES (544,'Ochlocknee',136);
INSERT INTO city(id,name,cId) VALUES (545,'Pavo',136);
INSERT INTO city(id,name,cId) VALUES (546,'Thomasville',136);
INSERT INTO city(id,name,cId) VALUES (547,'Brookfield',137);
INSERT INTO city(id,name,cId) VALUES (548,'Chula',137);
INSERT INTO city(id,name,cId) VALUES (549,'Omega',137);
INSERT INTO city(id,name,cId) VALUES (550,'Tifton',137);
INSERT INTO city(id,name,cId) VALUES (551,'Ty Ty',137);
INSERT INTO city(id,name,cId) VALUES (552,'Lyons',138);
INSERT INTO city(id,name,cId) VALUES (553,'Vidalia',138);
INSERT INTO city(id,name,cId) VALUES (554,'Hiawassee',139);
INSERT INTO city(id,name,cId) VALUES (555,'Young Harris',139);
INSERT INTO city(id,name,cId) VALUES (556,'Soperton',140);
INSERT INTO city(id,name,cId) VALUES (557,'Hogansville',141);
INSERT INTO city(id,name,cId) VALUES (558,'Lagrange',141);
INSERT INTO city(id,name,cId) VALUES (559,'West Point',141);
INSERT INTO city(id,name,cId) VALUES (560,'Ashburn',142);
INSERT INTO city(id,name,cId) VALUES (561,'Rebecca',142);
INSERT INTO city(id,name,cId) VALUES (562,'Sycamore',142);
INSERT INTO city(id,name,cId) VALUES (563,'Danville',143);
INSERT INTO city(id,name,cId) VALUES (564,'Dry Branch',143);
INSERT INTO city(id,name,cId) VALUES (565,'Jeffersonville',143);
INSERT INTO city(id,name,cId) VALUES (566,'Blairsville',144);
INSERT INTO city(id,name,cId) VALUES (567,'Suches',144);
INSERT INTO city(id,name,cId) VALUES (568,'The Rock',145);
INSERT INTO city(id,name,cId) VALUES (569,'Thomaston',145);
INSERT INTO city(id,name,cId) VALUES (570,'Yatesville',145);
INSERT INTO city(id,name,cId) VALUES (571,'Chickamauga',146);
INSERT INTO city(id,name,cId) VALUES (572,'Flintstone',146);
INSERT INTO city(id,name,cId) VALUES (573,'La Fayette',146);
INSERT INTO city(id,name,cId) VALUES (574,'Lookout Mountain',146);
INSERT INTO city(id,name,cId) VALUES (575,'Rock Spring',146);
INSERT INTO city(id,name,cId) VALUES (576,'Rossville',146);
INSERT INTO city(id,name,cId) VALUES (577,'Good Hope',147);
INSERT INTO city(id,name,cId) VALUES (578,'Jersey',147);
INSERT INTO city(id,name,cId) VALUES (579,'Loganville',147);
INSERT INTO city(id,name,cId) VALUES (580,'Monroe',147);
INSERT INTO city(id,name,cId) VALUES (581,'Social Circle',147);
INSERT INTO city(id,name,cId) VALUES (582,'Manor',148);
INSERT INTO city(id,name,cId) VALUES (583,'Millwood',148);
INSERT INTO city(id,name,cId) VALUES (584,'Waresboro',148);
INSERT INTO city(id,name,cId) VALUES (585,'Waycross',148);
INSERT INTO city(id,name,cId) VALUES (586,'Camak',149);
INSERT INTO city(id,name,cId) VALUES (587,'Jewell',149);
INSERT INTO city(id,name,cId) VALUES (588,'Mesena',149);
INSERT INTO city(id,name,cId) VALUES (589,'Norwood',149);
INSERT INTO city(id,name,cId) VALUES (590,'Warrenton',149);
INSERT INTO city(id,name,cId) VALUES (591,'Davisboro',150);
INSERT INTO city(id,name,cId) VALUES (592,'Harrison',150);
INSERT INTO city(id,name,cId) VALUES (593,'Oconee',150);
INSERT INTO city(id,name,cId) VALUES (594,'Sandersville',150);
INSERT INTO city(id,name,cId) VALUES (595,'Tennille',150);
INSERT INTO city(id,name,cId) VALUES (596,'Warthen',150);
INSERT INTO city(id,name,cId) VALUES (597,'Jesup',151);
INSERT INTO city(id,name,cId) VALUES (598,'Odum',151);
INSERT INTO city(id,name,cId) VALUES (599,'Screven',151);
INSERT INTO city(id,name,cId) VALUES (600,'Preston',152);
INSERT INTO city(id,name,cId) VALUES (601,'Weston',152);
INSERT INTO city(id,name,cId) VALUES (602,'Alamo',153);
INSERT INTO city(id,name,cId) VALUES (603,'Glenwood',153);
INSERT INTO city(id,name,cId) VALUES (604,'Cleveland',154);
INSERT INTO city(id,name,cId) VALUES (605,'Helen',154);
INSERT INTO city(id,name,cId) VALUES (606,'Sautee Nacoochee',154);
INSERT INTO city(id,name,cId) VALUES (607,'Cohutta',155);
INSERT INTO city(id,name,cId) VALUES (608,'Dalton',155);
INSERT INTO city(id,name,cId) VALUES (609,'Rocky Face',155);
INSERT INTO city(id,name,cId) VALUES (610,'Tunnel Hill',155);
INSERT INTO city(id,name,cId) VALUES (611,'Varnell',155);
INSERT INTO city(id,name,cId) VALUES (612,'Abbeville',156);
INSERT INTO city(id,name,cId) VALUES (613,'Pineview',156);
INSERT INTO city(id,name,cId) VALUES (614,'Pitts',156);
INSERT INTO city(id,name,cId) VALUES (615,'Rochelle',156);
INSERT INTO city(id,name,cId) VALUES (616,'Seville',156);
INSERT INTO city(id,name,cId) VALUES (617,'Rayle',157);
INSERT INTO city(id,name,cId) VALUES (618,'Tignall',157);
INSERT INTO city(id,name,cId) VALUES (619,'Washington',157);
INSERT INTO city(id,name,cId) VALUES (620,'Allentown',158);
INSERT INTO city(id,name,cId) VALUES (621,'Gordon',158);
INSERT INTO city(id,name,cId) VALUES (622,'Irwinton',158);
INSERT INTO city(id,name,cId) VALUES (623,'Mc Intyre',158);
INSERT INTO city(id,name,cId) VALUES (624,'Toomsboro',158);
INSERT INTO city(id,name,cId) VALUES (625,'Oakfield',159);
INSERT INTO city(id,name,cId) VALUES (626,'Poulan',159);
INSERT INTO city(id,name,cId) VALUES (627,'Sumner',159);
INSERT INTO city(id,name,cId) VALUES (628,'Sylvester',159);
INSERT INTO city(id,name,cId) VALUES (629,'Warwick',159);