INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (1,'Baxley',1,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (2,'Bristol',1,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (3,'Surrency',1,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (4,'Axson',2,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (5,'Pearson',2,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (6,'Willacoochee',2,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (7,'Alma',3,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (8,'Newton',4,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (9,'Hardwick',5,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (10,'Milledgeville',5,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (11,'Baldwin',6,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (12,'Homer',6,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (13,'Auburn',7,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (14,'Bethlehem',7,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (15,'Statham',7,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (16,'Winder',7,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (17,'Adairsville',8,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (18,'Cartersville',8,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (19,'Cassville',8,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (20,'Emerson',8,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (21,'Kingston',8,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (22,'Rydal',8,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (23,'Taylorsville',8,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (24,'White',8,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (25,'Fitzgerald',9,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (26,'Alapaha',10,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (27,'Enigma',10,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (28,'Nashville',10,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (29,'Ray City',10,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (30,'Lizella',11,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (31,'Macon',11,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (32,'Cochran',12,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (33,'Hoboken',13,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (34,'Hortense',13,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (35,'Nahunta',13,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (36,'Waynesville',13,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (37,'Barney',14,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (38,'Dixie',14,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (39,'Morven',14,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (40,'Quitman',14,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (41,'Ellabell',15,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (42,'Pembroke',15,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (43,'Richmond Hill',15,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (44,'Brooklet',16,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (45,'Portal',16,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (46,'Register',16,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (47,'Statesboro',16,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (48,'Girard',17,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (49,'Gough',17,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (50,'Keysville',17,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (51,'Sardis',17,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (52,'Waynesboro',17,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (53,'Flovilla',18,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (54,'Jackson',18,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (55,'Jenkinsburg',18,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (56,'Arlington',19,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (57,'Edison',19,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (58,'Leary',19,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (59,'Morgan',19,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (60,'Kings Bay',20,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (61,'Kingsland',20,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (62,'Saint Marys',20,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (63,'Waverly',20,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (64,'White Oak',20,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (65,'Woodbine',20,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (66,'Metter',21,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (67,'Pulaski',21,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (68,'Bowdon',22,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (69,'Bowdon Junction',22,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (70,'Carrollton',22,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (71,'Mount Zion',22,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (72,'Roopville',22,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (73,'Temple',22,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (74,'Villa Rica',22,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (75,'Waco',22,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (76,'Whitesburg',22,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (77,'Fort Oglethorpe',23,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (78,'Graysville',23,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (79,'Ringgold',23,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (80,'Folkston',24,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (81,'Saint George',24,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (82,'Pooler',25,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (83,'Savannah',25,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (84,'Tybee Island',25,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (85,'Cusseta',26,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (86,'Fort Benning',26,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (87,'Lyerly',27,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (88,'Menlo',27,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (89,'Summerville',27,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (90,'Trion',27,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (91,'Ball Ground',28,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (92,'Canton',28,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (93,'Holly Springs',28,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (94,'Lebanon',28,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (95,'Waleska',28,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (96,'Woodstock',28,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (97,'Athens',29,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (98,'Winterville',29,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (99,'Bluffton',30,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (100,'Fort Gaines',30,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (101,'Morris',30,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (102,'Conley',31,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (103,'Forest Park',31,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (104,'Jonesboro',31,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (105,'Lovejoy',31,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (106,'Morrow',31,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (107,'Rex',31,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (108,'Riverdale',31,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (109,'Esom Hill',31,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (110,'Argyle',32,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (111,'Du Pont',32,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (112,'Fargo',32,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (113,'Homerville',32,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (114,'Acworth',33,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (115,'Austell',33,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (116,'Clarkdale',33,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (117,'Kennesaw',33,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (118,'Mableton',33,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (119,'Marietta',33,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (120,'Powder Springs',33,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (121,'Smyrna',33,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (122,'Ambrose',34,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (123,'Broxton',34,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (124,'Douglas',34,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (125,'Nicholls',34,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (126,'West Green',34,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (127,'Berlin',35,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (128,'Doerun',35,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (129,'Ellenton',35,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (130,'Funston',35,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (131,'Hartsfield',35,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (132,'Moultrie',35,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (133,'Norman Park',35,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (134,'Appling',36,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (135,'Evans',36,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (136,'Grovetown',36,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (137,'Harlem',36,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (138,'Adel',37,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (139,'Cecil',37,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (140,'Lenox',37,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (141,'Sparks',37,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (142,'Grantville',38,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (143,'Haralson',38,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (144,'Moreland',38,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (145,'Newnan',38,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (146,'Sargent',38,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (147,'Senoia',38,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (148,'Sharpsburg',38,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (149,'Turin',38,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (150,'Knoxville',39,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (151,'Musella',39,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (152,'Roberta',39,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (153,'Arabi',40,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (154,'Cordele',40,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (155,'Rising Fawn',41,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (156,'Trenton',41,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (157,'Wildwood',41,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (158,'Dawsonville',42,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (159,'Attapulgus',43,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (160,'Bainbridge',43,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (161,'Brinson',43,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (162,'Climax',43,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (163,'Fowlstown',43,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (164,'Avondale Estates',44,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (165,'Clarkston',44,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (166,'Decatur',44,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (167,'Ellenwood',44,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (168,'Lithonia',44,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (169,'Pine Lake',44,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (170,'Redan',44,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (171,'Scottdale',44,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (172,'Stone Mountain',44,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (173,'Tucker',44,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (174,'Chauncey',45,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (175,'Chester',45,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (176,'Eastman',45,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (177,'Rhine',45,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (178,'Byromville',46,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (179,'Lilly',46,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (180,'Pinehurst',46,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (181,'Unadilla',46,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (182,'Vienna',46,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (183,'Albany',47,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (184,'Putney',47,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (185,'Douglasville',48,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (186,'Lithia Springs',48,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (187,'Winston',48,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (188,'Blakely',49,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (189,'Cedar Springs',49,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (190,'Damascus',49,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (191,'Jakin',49,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (192,'Statenville',50,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (193,'Bloomingdale',51,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (194,'Clyo',51,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (195,'Eden',51,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (196,'Guyton',51,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (197,'Meldrim',51,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (198,'Rincon',51,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (199,'Springfield',51,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (200,'Bowman',52,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (201,'Dewy Rose',52,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (202,'Elberton',52,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (203,'Adrian',53,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (204,'Garfield',53,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (205,'Midville',53,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (206,'Norristown',53,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (207,'Nunez',53,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (208,'Stillmore',53,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (209,'Swainsboro',53,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (210,'Twin City',53,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (211,'Bellville',54,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (212,'Claxton',54,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (213,'Daisy',54,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (214,'Hagan',54,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (215,'Blue Ridge',55,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (216,'Epworth',55,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (217,'Mc Caysville',55,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (218,'Mineral Bluff',55,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (219,'Morganton',55,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (220,'Brooks',56,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (221,'Fayetteville',56,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (222,'Peachtree City',56,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (223,'Tyrone',56,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (224,'Armuchee',57,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (225,'Cave Spring',57,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (226,'Coosa',57,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (227,'Lindale',57,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (228,'Mount Berry',57,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (229,'Rome',57,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (230,'Shannon',57,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (231,'Silver Creek',57,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (232,'Cumming',58,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (233,'Canon',59,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (234,'Carnesville',59,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (235,'Franklin Springs',59,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (236,'Lavonia',59,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (237,'Royston',59,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (238,'Alpharetta',60,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (239,'Atlanta',60,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (240,'Fairburn',60,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (241,'Palmetto',60,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (242,'Red Oak',60,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (243,'Roswell',60,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (244,'Union City',60,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (245,'Cherry Log',61,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (246,'East Ellijay',61,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (247,'Ellijay',61,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (248,'Gibson',62,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (249,'Mitchell',62,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (250,'Brunswick',63,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (251,'Jekyll Island',63,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (252,'Saint Simons Island',63,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (253,'Sea Island',63,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (254,'Calhoun',64,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (255,'Fairmount',64,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (256,'Oakman',64,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (257,'Plainville',64,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (258,'Ranger',64,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (259,'Resaca',64,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (260,'Sugar Valley',64,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (261,'Cairo',65,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (262,'Calvary',65,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (263,'Whigham',65,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (264,'Greensboro',66,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (265,'Siloam',66,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (266,'Union Point',66,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (267,'White Plains',66,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (268,'Buford',67,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (269,'Dacula',67,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (270,'Duluth',67,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (271,'Grayson',67,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (272,'Lawrenceville',67,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (273,'Lilburn',67,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (274,'Norcross',67,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (275,'North Metro',67,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (276,'Snellville',67,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (277,'Suwanee',67,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (278,'Alto',68,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (279,'Clarkesville',68,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (280,'Cornelia',68,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (281,'Demorest',68,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (282,'Habersham',68,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (283,'Mount Airy',68,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (284,'Turnerville',68,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (285,'Chestnut Mountain',69,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (286,'Clermont',69,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (287,'Flowery Branch',69,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (288,'Gainesville',69,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (289,'Gillsville',69,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (290,'Lula',69,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (291,'Murrayville',69,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (292,'Oakwood',69,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (293,'Sparta',70,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (294,'Bremen',71,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (295,'Buchanan',71,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (296,'Felton',71,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (297,'Tallapoosa',71,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (298,'Cataula',72,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (299,'Ellerslie',72,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (300,'Fortson',72,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (301,'Hamilton',72,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (302,'Pine Mountain',72,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (303,'Pine Mountain Valley',72,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (304,'Shiloh',72,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (305,'Waverly Hall',72,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (306,'Bowersville',73,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (307,'Hartwell',73,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (308,'Franklin',74,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (309,'Glenn',74,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (310,'Hampton',75,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (311,'Locust Grove',75,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (312,'Mcdonough',75,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (313,'Stockbridge',75,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (314,'Bonaire',76,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (315,'Centerville',76,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (316,'Clinchfield',76,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (317,'Elko',76,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (318,'Kathleen',76,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (319,'Perry',76,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (320,'Warner Robins',76,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (321,'Irwinville',77,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (322,'Mystic',77,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (323,'Ocilla',77,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (324,'Wray',77,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (325,'Braselton',78,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (326,'Commerce',78,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (327,'Hoschton',78,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (328,'Jefferson',78,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (329,'Maysville',78,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (330,'Nicholson',78,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (331,'Pendergrass',78,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (332,'Talmo',78,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (333,'Hillsboro',79,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (334,'Mansfield',79,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (335,'Monticello',79,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (336,'Newborn',79,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (337,'Shady Dale',79,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (338,'Denton',80,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (339,'Hazlehurst',80,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (340,'Avera',81,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (341,'Bartow',81,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (342,'Louisville',81,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (343,'Matthews',81,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (344,'Stapleton',81,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (345,'Wadley',81,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (346,'Wrens',81,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (347,'Millen',82,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (348,'Perkins',82,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (349,'Kite',83,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (350,'Wrightsville',83,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (351,'Gray',84,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (352,'Haddock',84,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (353,'Barnesville',85,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (354,'Milner',85,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (355,'Lakeland',86,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (356,'Stockton',86,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (357,'Cadwell',87,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (358,'Dexter',87,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (359,'Dublin',87,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (360,'Dudley',87,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (361,'East Dublin',87,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (362,'Montrose',87,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (363,'Rentz',87,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (364,'Rockledge',87,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (365,'Leesburg',88,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (366,'Smithville',88,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (367,'Allenhurst',89,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (368,'Fleming',89,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (369,'Fort Stewart',89,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (370,'Hinesville',89,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (371,'Midway',89,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (372,'Riceboro',89,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (373,'Walthourville',89,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (374,'Lincolnton',90,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (375,'Ludowici',91,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (376,'Hahira',92,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (377,'Lake Park',92,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (378,'Moody A F B',92,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (379,'Naylor',92,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (380,'Valdosta',92,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (381,'Dahlonega',93,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (382,'Ideal',94,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (383,'Marshallville',94,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (384,'Montezuma',94,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (385,'Oglethorpe',94,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (386,'Colbert',95,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (387,'Comer',95,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (388,'Danielsville',95,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (389,'Hull',95,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (390,'Ila',95,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (391,'Box Springs',96,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (392,'Buena Vista',96,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (393,'Mauk',96,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (394,'Boneville',97,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (395,'Dearing',97,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (396,'Thomson',97,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (397,'Crescent',98,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (398,'Darien',98,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (399,'Meridian',98,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (400,'Sapelo Island',98,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (401,'Townsend',98,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (402,'Gay',99,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (403,'Greenville',99,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (404,'Luthersville',99,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (405,'Manchester',99,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (406,'Warm Springs',99,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (407,'Woodbury',99,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (408,'Colquitt',100,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (409,'Baconton',101,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (410,'Camilla',101,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (411,'Cotton',101,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (412,'Pelham',101,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (413,'Sale City',101,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (414,'Bolingbroke',102,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (415,'Culloden',102,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (416,'Forsyth',102,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (417,'Juliette',102,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (418,'Smarr',102,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (419,'Ailey',103,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (420,'Alston',103,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (421,'Mount Vernon',103,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (422,'Tarrytown',103,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (423,'Uvalda',103,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (424,'Bostwick',104,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (425,'Buckhead',104,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (426,'Madison',104,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (427,'Rutledge',104,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (428,'Chatsworth',105,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (429,'Cisco',105,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (430,'Crandall',105,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (431,'Eton',105,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (432,'Tennga',105,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (433,'Columbus',106,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (434,'Midland',106,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (435,'Upatoi',106,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (436,'Covington',107,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (437,'Oxford',107,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (438,'Porterdale',107,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (439,'Bishop',108,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (440,'Bogart',108,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (441,'Farmington',108,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (442,'Watkinsville',108,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (443,'Arnoldsville',109,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (444,'Carlton',109,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (445,'Crawford',109,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (446,'Lexington',109,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (447,'Maxeys',109,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (448,'Stephens',109,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (449,'Dallas',110,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (450,'Hiram',110,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (451,'Byron',111,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (452,'Fort Valley',111,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (453,'Jasper',112,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (454,'Marble Hill',112,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (455,'Nelson',112,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (456,'Talking Rock',112,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (457,'Tate',112,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (458,'Blackshear',113,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (459,'Mershon',113,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (460,'Offerman',113,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (461,'Patterson',113,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (462,'Concord',114,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (463,'Meansville',114,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (464,'Molena',114,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (465,'Williamson',114,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (466,'Zebulon',114,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (467,'Aragon',115,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (468,'Cedartown',115,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (469,'Rockmart',115,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (470,'Hawkinsville',116,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (471,'Eatonton',117,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (472,'Georgetown',118,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (473,'Clayton',119,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (474,'Dillard',119,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (475,'Lakemont',119,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (476,'Mountain City',119,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (477,'Rabun Gap',119,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (478,'Tallulah Falls',119,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (479,'Tiger',119,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (480,'Wiley',119,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (481,'Coleman',120,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (482,'Cuthbert',120,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (483,'Shellman',120,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (484,'Augusta',121,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (485,'Blythe',121,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (486,'Gracewood',121,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (487,'Hephzibah',121,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (488,'Conyers',122,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (489,'Ellaville',123,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (490,'Dover',124,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (491,'Newington',124,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (492,'Oliver',124,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (493,'Rocky Ford',124,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (494,'Sylvania',124,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (495,'Donalsonville',125,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (496,'Iron City',125,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (497,'Experiment',126,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (498,'Griffin',126,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (499,'Orchard Hill',126,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (500,'Sunny Side',126,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (501,'Eastanollee',127,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (502,'Martin',127,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (503,'Toccoa',127,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (504,'Toccoa Falls',127,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (505,'Louvale',128,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (506,'Lumpkin',128,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (507,'Omaha',128,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (508,'Richland',128,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (509,'Americus',129,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (510,'Andersonville',129,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (511,'Cobb',129,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (512,'De Soto',129,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (513,'Leslie',129,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (514,'Plains',129,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (515,'Geneva',130,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (516,'Junction City',130,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (517,'Talbotton',130,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (518,'Woodland',130,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (519,'Crawfordville',131,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (520,'Sharon',131,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (521,'Cobbtown',132,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (522,'Collins',132,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (523,'Glennville',132,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (524,'Manassas',132,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (525,'Reidsville',132,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (526,'Butler',133,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (527,'Howard',133,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (528,'Reynolds',133,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (529,'Rupert',133,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (530,'Helena',134,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (531,'Jacksonville',134,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (532,'Lumber City',134,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (533,'Mc Rae',134,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (534,'Milan',134,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (535,'Scotland',134,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (536,'Bronwood',135,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (537,'Dawson',135,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (538,'Parrott',135,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (539,'Sasser',135,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (540,'Barwick',136,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (541,'Boston',136,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (542,'Coolidge',136,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (543,'Meigs',136,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (544,'Ochlocknee',136,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (545,'Pavo',136,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (546,'Thomasville',136,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (547,'Brookfield',137,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (548,'Chula',137,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (549,'Omega',137,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (550,'Tifton',137,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (551,'Ty Ty',137,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (552,'Lyons',138,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (553,'Vidalia',138,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (554,'Hiawassee',139,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (555,'Young Harris',139,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (556,'Soperton',140,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (557,'Hogansville',141,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (558,'Lagrange',141,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (559,'West Point',141,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (560,'Ashburn',142,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (561,'Rebecca',142,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (562,'Sycamore',142,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (563,'Danville',143,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (564,'Dry Branch',143,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (565,'Jeffersonville',143,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (566,'Blairsville',144,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (567,'Suches',144,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (568,'The Rock',145,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (569,'Thomaston',145,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (570,'Yatesville',145,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (571,'Chickamauga',146,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (572,'Flintstone',146,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (573,'La Fayette',146,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (574,'Lookout Mountain',146,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (575,'Rock Spring',146,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (576,'Rossville',146,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (577,'Good Hope',147,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (578,'Jersey',147,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (579,'Loganville',147,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (580,'Monroe',147,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (581,'Social Circle',147,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (582,'Manor',148,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (583,'Millwood',148,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (584,'Waresboro',148,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (585,'Waycross',148,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (586,'Camak',149,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (587,'Jewell',149,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (588,'Mesena',149,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (589,'Norwood',149,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (590,'Warrenton',149,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (591,'Davisboro',150,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (592,'Harrison',150,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (593,'Oconee',150,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (594,'Sandersville',150,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (595,'Tennille',150,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (596,'Warthen',150,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (597,'Jesup',151,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (598,'Odum',151,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (599,'Screven',151,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (600,'Preston',152,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (601,'Weston',152,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (602,'Alamo',153,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (603,'Glenwood',153,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (604,'Cleveland',154,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (605,'Helen',154,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (606,'Sautee Nacoochee',154,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (607,'Cohutta',155,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (608,'Dalton',155,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (609,'Rocky Face',155,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (610,'Tunnel Hill',155,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (611,'Varnell',155,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (612,'Abbeville',156,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (613,'Pineview',156,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (614,'Pitts',156,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (615,'Rochelle',156,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (616,'Seville',156,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (617,'Rayle',157,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (618,'Tignall',157,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (619,'Washington',157,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (620,'Allentown',158,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (621,'Gordon',158,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (622,'Irwinton',158,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (623,'Mc Intyre',158,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (624,'Toomsboro',158,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (625,'Oakfield',159,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (626,'Poulan',159,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (627,'Sumner',159,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (628,'Sylvester',159,NOW(),NOW());
INSERT INTO cities (id,name,cId,createdAt,updatedAt) VALUES (629,'Warwick',159,NOW(),NOW());